version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/cars:/data/cars
    env_file:
    - .env
  server:
    build: .
    depends_on:
      - postgres
    image: carapi_server
    env_file: .env
    ports:
      - "3000:3000"
